const app=document.querySelector('.ar-app');const video=document.getElementById('camera');const fallback=document.getElementById('cameraFallback');const plant=document.getElementById('placedPlant');const hint=document.getElementById('hint');const statusText=document.getElementById('statusText');const toast=document.getElementById('toast');const panel=document.getElementById('plantPanel');const badgeCount=document.getElementById('badgeCount');let placed=false,scale=1,rotation=0,mode='plant',plantIndex=0,badges=Number(localStorage.getItem('flower-ar-badges')||0);badgeCount.textContent=Math.min(badges,3);
const plantNames=['一品紅','紫色數位花','金色生態花'];const plantDescs=['透過 AR 植物展示，使用者可以在真實場域中觀察數位植物，並進一步了解植物知識與地方生態。','以數位植物作為文化導覽媒介，讓學習從閱讀轉為可操作、可探索的體驗。','透過遊戲化蒐集與植物展示，將地方生態知識融入探索任務。'];
async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();fallback.style.display='none';statusText.textContent='點擊畫面放置植物'}catch(e){fallback.style.display='grid';statusText.textContent='請允許相機權限';showToast('無法啟動相機，請檢查瀏覽器權限')}}startCamera();
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function setPlantPosition(x,y){plant.style.left=x+'px';plant.style.top=y+'px';plant.style.transform=`translate(-50%,-78%) scale(${scale}) rotate(${rotation}deg)`}
app.addEventListener('click',e=>{if(e.target.closest('.ar-topbar,.hud,.ar-toolbar,.plant-panel,.marker-modal'))return;if(mode==='plant'){if(!placed){placed=true;plant.classList.add('visible');hint.textContent='拖曳植物可調整位置';statusText.textContent='植物已放置';showToast('植物已放置到 AR 場景')}setPlantPosition(e.clientX,e.clientY)}});
let drag=false,dragStart=null;
plant.addEventListener('pointerdown',e=>{drag=true;dragStart={x:e.clientX,y:e.clientY,scale,rotation,left:plant.offsetLeft,top:plant.offsetTop};plant.setPointerCapture(e.pointerId);e.stopPropagation()});
plant.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;if(mode==='rotate'){rotation=dragStart.rotation+dx*.8;setPlantPosition(plant.offsetLeft,plant.offsetTop)}else if(mode==='scale'){scale=Math.max(.45,Math.min(2.2,dragStart.scale-dy/180));setPlantPosition(plant.offsetLeft,plant.offsetTop)}else{setPlantPosition(dragStart.left+dx,dragStart.top+dy)}});
plant.addEventListener('pointerup',()=>drag=false);plant.addEventListener('pointercancel',()=>drag=false);
document.querySelectorAll('.ar-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.action;document.querySelectorAll('.ar-toolbar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');app.classList.remove('rotate-mode','scale-mode');if(action==='plant'){mode='plant';plantIndex=(plantIndex+1)%3;plant.className='placed-plant visible plant-'+['a','b','c'][plantIndex];document.getElementById('plantName').textContent=plantNames[plantIndex];document.getElementById('plantDesc').textContent=plantDescs[plantIndex];showToast('已切換植物')}else if(action==='rotate'){mode='rotate';app.classList.add('rotate-mode');showToast('左右拖曳植物即可旋轉')}else if(action==='scale'){mode='scale';app.classList.add('scale-mode');showToast('上下拖曳植物調整大小')}else if(action==='reset'){mode='plant';scale=1;rotation=0;placed=false;plant.classList.remove('visible');hint.textContent='輕點畫面，將植物放進環境中';statusText.textContent='點擊畫面放置植物';showToast('AR 場景已重設')}else if(action==='marker'){document.getElementById('markerModal').classList.add('open');document.getElementById('markerModal').setAttribute('aria-hidden','false')}}));
document.getElementById('infoBtn').addEventListener('click',()=>panel.classList.add('open'));document.getElementById('closePanel').addEventListener('click',()=>panel.classList.remove('open'));
document.getElementById('collectBtn').addEventListener('click',()=>{if(badges<3){badges++;localStorage.setItem('flower-ar-badges',badges);badgeCount.textContent=badges;showToast('獲得 1 枚生態徽章 ✦')}else showToast('你已蒐集完成所有示範徽章')});
const markerModal=document.getElementById('markerModal');document.getElementById('markerClose').addEventListener('click',()=>markerModal.classList.remove('open'));markerModal.addEventListener('click',e=>{if(e.target===markerModal)markerModal.classList.remove('open')});
window.addEventListener('beforeunload',()=>{const s=video.srcObject;if(s)s.getTracks().forEach(t=>t.stop())});
