const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const app=$('.ar-app'),video=$('#camera'),fallback=$('#cameraFallback'),plant=$('#placedPlant'),hint=$('#hint'),statusText=$('#statusText'),toast=$('#toast'),panel=$('#plantPanel'),drawer=$('#plantDrawer');
const plants=[
{name:'互葉白千層',latin:'Melaleuca alternifolia',image:'assets/影印/互葉白千層 (Melaleuca alternifolia).webp'},
{name:'木瓜',latin:'PROJECT PLANT',image:'assets/影印/木瓜.webp'},
{name:'左手香',latin:'PROJECT PLANT',image:'assets/影印/左手香2.webp',model:{folder:'assets/植物大將軍/左手香/',mtl:'tripo_convert_8a6ca7b5-4c33-494c-b569-6bdecf61d62e.mtl',obj:'tripo_convert_8a6ca7b5-4c33-494c-b569-6bdecf61d62e.obj'}},
{name:'杭菊',latin:'PROJECT PLANT',image:'assets/影印/杭菊.webp'},
{name:'粉尊鼠尾草',latin:'PROJECT PLANT',image:'assets/影印/粉尊鼠尾草.webp'},
{name:'斑艾',latin:'Crossostephium chinense',image:'assets/影印/斑艾 (Crossostephium chinense).webp',model:{folder:'assets/植物大將軍/斑艾 (Crossostephium chinense)/',mtl:'tripo_convert_471ccb88-a7ff-4c4e-9ef7-e8e82d583307.mtl',obj:'tripo_convert_471ccb88-a7ff-4c4e-9ef7-e8e82d583307.obj'}},
{name:'黑板樹',latin:'PROJECT PLANT',image:'assets/影印/黑板樹.webp'},
{name:'聖誕紅',latin:'PROJECT PLANT',image:'assets/影印/聖誕紅.webp'},
{name:'變葉木',latin:'PROJECT PLANT',image:'assets/影印/變葉木.webp',model:{folder:'assets/植物大將軍/變葉木/',mtl:'tripo_convert_b123a718-6b3f-457a-8d63-28c396622362.mtl',obj:'tripo_convert_b123a718-6b3f-457a-8d63-28c396622362.obj'}},
{name:'鱗蓋鳳尾蕨',latin:'Pteris vittata',image:'assets/影印/鱗蓋鳳尾蕨 (Pteris vittata).webp',model:{folder:'assets/植物大將軍/鱗蓋鳳尾蕨 (Pteris vittata)/',mtl:'tripo_convert_88a3e4ce-c2f1-4b60-bab1-65ef0ba163de.mtl',obj:'tripo_convert_88a3e4ce-c2f1-4b60-bab1-65ef0ba163de.obj'}}
];
let placed=false,scale=1,rotation=0,mode='plant',plantIndex=0;let collected=JSON.parse(localStorage.getItem('flower-ar-plants')||'[]');let missionProgress=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');
$('#missionCount').textContent=missionProgress.filter(Boolean).length;$('#plantBadgeCount').textContent=collected.length;
async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();fallback.style.display='none';statusText.textContent='點擊畫面放置植物'}catch(e){fallback.style.display='grid';statusText.textContent='請允許相機權限';showToast('無法啟動相機，請檢查瀏覽器權限')}}startCamera();
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1700)}
function setPos(x,y){plant.style.left=x+'px';plant.style.top=y+'px';plant.style.transform=`translate(-50%,-78%) scale(${scale})`;if(window.Plant3D?.active){window.Plant3D.setRotation(rotation*Math.PI/180)}else{$('#plantImage').style.transform=`rotate(${rotation}deg)`}}
async function applyPlant(i){
  plantIndex=i;const p=plants[i];$('#plantName').textContent=p.name;$('#plantLatin').textContent=p.latin;
  $$('#plantList button').forEach((b,n)=>b.classList.toggle('active',n===i));
  $('#collectBtn').textContent=collected.includes(p.name)?'已蒐集此植物 ✓':'蒐集這株植物徽章';
  const img=$('#plantImage'),status=$('#modelStatus');img.src=p.image;img.classList.add('active');plant.classList.remove('model3d');status.textContent=p.model?'準備載入 OBJ…':'2D PROJECT ASSET';
  window.Plant3D?.clear?.();
  if(p.model){
    let tries=0;while(!window.Plant3D&&tries<40){await new Promise(r=>setTimeout(r,50));tries++}
    if(window.Plant3D){const ok=await window.Plant3D.load(p.model);if(ok){img.classList.remove('active');plant.classList.add('model3d');status.textContent='OBJ 3D MODEL'}else{img.classList.add('active');status.textContent='2D FALLBACK'}}
  }
}
function renderPlantList(){plants.forEach((p,i)=>{const b=document.createElement('button');b.innerHTML=p.name+'<small>'+p.latin+'</small>';b.onclick=()=>{applyPlant(i);drawer.classList.remove('open');mode='plant';$$('.ar-toolbar button').forEach(x=>x.classList.remove('active'));$('[data-action="plant"]').classList.add('active');showToast('已選擇 '+p.name)};$('#plantList').appendChild(b)});const q=new URLSearchParams(location.search).get('plant');const found=plants.findIndex(p=>p.name===q);applyPlant(found>=0?found:0)}renderPlantList();
app.addEventListener('click',e=>{if(e.target.closest('.ar-topbar,.hud,.ar-toolbar,.plant-panel,.plant-drawer,.marker-modal'))return;if(mode==='plant'){if(!placed){placed=true;plant.classList.add('visible');hint.textContent='拖曳植物可調整位置';statusText.textContent='植物已放置';showToast('植物已放置到 AR 場景')}setPos(e.clientX,e.clientY)}});
let drag=false,start=null;plant.addEventListener('pointerdown',e=>{drag=true;start={x:e.clientX,y:e.clientY,scale,rotation,left:plant.offsetLeft,top:plant.offsetTop};plant.setPointerCapture(e.pointerId);e.stopPropagation()});plant.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(mode==='rotate'){rotation=start.rotation+dx*.8;window.Plant3D?.setAutoRotate?.(false);setPos(plant.offsetLeft,plant.offsetTop)}else if(mode==='scale'){scale=Math.max(.45,Math.min(2.2,start.scale-dy/180));setPos(plant.offsetLeft,plant.offsetTop)}else setPos(start.left+dx,start.top+dy)});plant.addEventListener('pointerup',()=>drag=false);plant.addEventListener('pointercancel',()=>drag=false);
$$('.ar-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action;$$('.ar-toolbar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');app.classList.remove('rotate-mode','scale-mode');if(a==='plant'){mode='plant';drawer.classList.add('open')}else if(a==='rotate'){mode='rotate';app.classList.add('rotate-mode');window.Plant3D?.setAutoRotate?.(false);showToast('左右拖曳植物即可 360° 旋轉')}else if(a==='scale'){mode='scale';app.classList.add('scale-mode');showToast('上下拖曳植物調整大小')}else if(a==='reset'){mode='plant';scale=1;rotation=0;window.Plant3D?.setRotation?.(0);window.Plant3D?.setAutoRotate?.(true);placed=false;plant.classList.remove('visible');hint.textContent='輕點畫面，將植物放進環境中';statusText.textContent='點擊畫面放置植物';showToast('AR 場景已重設')}else if(a==='marker')$('#markerModal').classList.add('open')}));
$('#infoBtn').onclick=()=>panel.classList.add('open');$('#closePanel').onclick=()=>panel.classList.remove('open');$('#drawerClose').onclick=()=>drawer.classList.remove('open');
$('#collectBtn').onclick=()=>{const n=plants[plantIndex].name;if(collected.includes(n))return showToast('這株植物已經蒐集過了');collected.push(n);localStorage.setItem('flower-ar-plants',JSON.stringify(collected));$('#plantBadgeCount').textContent=collected.length;applyPlant(plantIndex);showToast('蒐集 '+n+' 徽章 ✦')};
const marker=$('#markerModal');$('#markerClose').onclick=()=>marker.classList.remove('open');marker.addEventListener('click',e=>{if(e.target===marker)marker.classList.remove('open')});window.addEventListener('storage',()=>{missionProgress=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');$('#missionCount').textContent=missionProgress.filter(Boolean).length});window.addEventListener('beforeunload',()=>{const s=video.srcObject;if(s)s.getTracks().forEach(t=>t.stop())});