const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const app=$('.ar-app'),video=$('#camera'),fallback=$('#cameraFallback'),plant=$('#placedPlant'),hint=$('#hint'),statusText=$('#statusText'),toast=$('#toast'),panel=$('#plantPanel'),drawer=$('#plantDrawer');
const plants=[
{name:'互葉白千層',latin:'Melaleuca alternifolia',image:'assets/影印/互葉白千層 (Melaleuca alternifolia).webp'},
{name:'木瓜',latin:'PROJECT PLANT',image:'assets/影印/木瓜.webp'},
{name:'左手香',latin:'PROJECT PLANT',image:'assets/影印/左手香2.webp'},
{name:'杭菊',latin:'PROJECT PLANT',image:'assets/影印/杭菊.webp'},
{name:'粉尊鼠尾草',latin:'PROJECT PLANT',image:'assets/影印/粉尊鼠尾草.webp'},
{name:'斑艾',latin:'Crossostephium chinense',image:'assets/影印/斑艾 (Crossostephium chinense).webp'},
{name:'黑板樹',latin:'PROJECT PLANT',image:'assets/影印/黑板樹.webp'},
{name:'聖誕紅',latin:'PROJECT PLANT',image:'assets/影印/聖誕紅.webp'},
{name:'變葉木',latin:'PROJECT PLANT',image:'assets/影印/變葉木.webp'},
{name:'鱗蓋鳳尾蕨',latin:'Pteris vittata',image:'assets/影印/鱗蓋鳳尾蕨 (Pteris vittata).webp'}
];
let placed=false,scale=1,rotation=0,mode='plant',plantIndex=0;let collected=JSON.parse(localStorage.getItem('flower-ar-plants')||'[]');let missionProgress=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');
$('#missionCount').textContent=missionProgress.filter(Boolean).length;$('#plantBadgeCount').textContent=collected.length;
async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();fallback.style.display='none';statusText.textContent='點擊畫面放置植物'}catch(e){fallback.style.display='grid';statusText.textContent='請允許相機權限';showToast('無法啟動相機，請檢查瀏覽器權限')}}startCamera();
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1700)}
function setPos(x,y){plant.style.left=x+'px';plant.style.top=y+'px';plant.style.transform=`translate(-50%,-78%) scale(${scale}) rotate(${rotation}deg)`}
async function applyPlant(i){plantIndex=i;const p=plants[i];$('#plantName').textContent=p.name;$('#plantLatin').textContent=p.latin;$('#plantList button').forEach((b,n)=>b.classList.toggle('active',n===i));$('#collectBtn').textContent=collected.includes(p.name)?'已蒐集此植物 ✓':'蒐集這株植物徽章';const img=$('#plantImage'),model=$('#plantModel'),status=$('#modelStatus');img.src=p.image;img.classList.add('active');model.classList.remove('active');model.removeAttribute('src');status.textContent='2D PROJECT ASSET';const candidates=[`assets/植物大將軍/${p.name}/${p.name}.glb`,`assets/植物大將軍/${p.name}/model.glb`];for(const path of candidates){try{const r=await fetch(path,{method:'HEAD'});if(r.ok){model.src=path;model.classList.add('active');img.classList.remove('active');status.textContent='3D MODEL';break}}catch(e){}}}
function renderPlantList(){plants.forEach((p,i)=>{const b=document.createElement('button');b.innerHTML=p.name+'<small>'+p.latin+'</small>';b.onclick=()=>{applyPlant(i);drawer.classList.remove('open');mode='plant';$$('.ar-toolbar button').forEach(x=>x.classList.remove('active'));$('[data-action="plant"]').classList.add('active');showToast('已選擇 '+p.name)};$('#plantList').appendChild(b)});const q=new URLSearchParams(location.search).get('plant');const found=plants.findIndex(p=>p.name===q);applyPlant(found>=0?found:0)}renderPlantList();
app.addEventListener('click',e=>{if(e.target.closest('.ar-topbar,.hud,.ar-toolbar,.plant-panel,.plant-drawer,.marker-modal'))return;if(mode==='plant'){if(!placed){placed=true;plant.classList.add('visible');hint.textContent='拖曳植物可調整位置';statusText.textContent='植物已放置';showToast('植物已放置到 AR 場景')}setPos(e.clientX,e.clientY)}});
let drag=false,start=null;plant.addEventListener('pointerdown',e=>{drag=true;start={x:e.clientX,y:e.clientY,scale,rotation,left:plant.offsetLeft,top:plant.offsetTop};plant.setPointerCapture(e.pointerId);e.stopPropagation()});plant.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(mode==='rotate'){rotation=start.rotation+dx*.8;setPos(plant.offsetLeft,plant.offsetTop)}else if(mode==='scale'){scale=Math.max(.45,Math.min(2.2,start.scale-dy/180));setPos(plant.offsetLeft,plant.offsetTop)}else setPos(start.left+dx,start.top+dy)});plant.addEventListener('pointerup',()=>drag=false);plant.addEventListener('pointercancel',()=>drag=false);
$$('.ar-toolbar button').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action;$$('.ar-toolbar button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');app.classList.remove('rotate-mode','scale-mode');if(a==='plant'){mode='plant';drawer.classList.add('open')}else if(a==='rotate'){mode='rotate';app.classList.add('rotate-mode');showToast('左右拖曳植物即可旋轉')}else if(a==='scale'){mode='scale';app.classList.add('scale-mode');showToast('上下拖曳植物調整大小')}else if(a==='reset'){mode='plant';scale=1;rotation=0;placed=false;plant.classList.remove('visible');hint.textContent='輕點畫面，將植物放進環境中';statusText.textContent='點擊畫面放置植物';showToast('AR 場景已重設')}else if(a==='marker')$('#markerModal').classList.add('open')}));
$('#infoBtn').onclick=()=>panel.classList.add('open');$('#closePanel').onclick=()=>panel.classList.remove('open');$('#drawerClose').onclick=()=>drawer.classList.remove('open');
$('#collectBtn').onclick=()=>{const n=plants[plantIndex].name;if(collected.includes(n))return showToast('這株植物已經蒐集過了');collected.push(n);localStorage.setItem('flower-ar-plants',JSON.stringify(collected));$('#plantBadgeCount').textContent=collected.length;applyPlant(plantIndex);showToast('蒐集 '+n+' 徽章 ✦')};
const marker=$('#markerModal');$('#markerClose').onclick=()=>marker.classList.remove('open');marker.addEventListener('click',e=>{if(e.target===marker)marker.classList.remove('open')});window.addEventListener('storage',()=>{missionProgress=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');$('#missionCount').textContent=missionProgress.filter(Boolean).length});window.addEventListener('beforeunload',()=>{const s=video.srcObject;if(s)s.getTracks().forEach(t=>t.stop())});