const $=(s,c=document)=>c.querySelector(s),stage=$('#stage'),runner=$('#runner');let running=false,distance=0,energy=0,life=3,speed=310,last=0,spawnAt=0,coinAt=0,objects=[],raf,jumps=0,invincible=false;
function ui(){distanceEl.textContent=Math.floor(distance)+'m';energyEl.textContent=energy;lifeEl.textContent='♥'.repeat(life)+'♡'.repeat(3-life)}const distanceEl=$('#distance'),energyEl=$('#energy'),lifeEl=$('#life');
function jump(){if(!running||jumps>=2)return;jumps++;runner.classList.remove('jump','double');void runner.offsetWidth;runner.classList.add(jumps===1?'jump':'double');setTimeout(()=>{if(jumps===1)jumps=0;else jumps=0;runner.classList.remove('jump','double')},jumps===1?480:500)}
stage.addEventListener('pointerdown',jump);window.addEventListener('keydown',e=>{if(e.code==='Space'||e.key==='ArrowUp'){e.preventDefault();jump()}});
function spawnObstacle(){const el=document.createElement('div'),types=['',' tall',' low'];el.className='obstacle'+types[Math.floor(Math.random()*types.length)];stage.appendChild(el);objects.push({el,x:stage.clientWidth+80,type:'obstacle'})}
function spawnCoin(){const el=document.createElement('div');el.className='leaf-coin';const heights=[135,190,245];el.style.bottom=heights[Math.floor(Math.random()*heights.length)]+'px';stage.appendChild(el);objects.push({el,x:stage.clientWidth+50,type:'coin'})}
function lines(){for(let i=0;i<3;i++){const l=document.createElement('i');l.style.left=(stage.clientWidth+Math.random()*120)+'px';l.style.top=(60+Math.random()*(stage.clientHeight-150))+'px';$('#speedLines').appendChild(l);setTimeout(()=>l.remove(),500)}}
function collide(a,b){return !(a.right<b.left+8||a.left>b.right-8||a.bottom<b.top+8||a.top>b.bottom-8)}
function hit(){if(invincible)return;life--;ui();runner.classList.add('hit','invincible');invincible=true;setTimeout(()=>{runner.classList.remove('hit','invincible');invincible=false},1000);if(life<=0)finish(false)}
function finish(win){running=false;cancelAnimationFrame(raf);objects.forEach(o=>o.el.remove());objects=[];if(win){const p=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');p[3]=true;localStorage.setItem('flower-web-missions',JSON.stringify(p));$('#resultIcon').textContent='✦';$('#resultTitle').textContent='地方探索完成';$('#resultText').textContent='你跑了 '+Math.floor(distance)+'m，收集 '+energy+' 枚能量葉。MISSION 04 徽章已解鎖。'}else{$('#resultIcon').textContent='×';$('#resultTitle').textContent='探索中斷';$('#resultText').textContent='本次距離 '+Math.floor(distance)+'m。注意障礙類型並善用雙跳。'}$('#result').classList.remove('hidden')}
function tick(t){if(!running)return;const dt=Math.min((t-last)/1000,.035);last=t;distance+=dt*(speed/6.2);speed=Math.min(520,310+distance*.36);if(distance>=500)return finish(true);if(t>spawnAt){spawnObstacle();spawnAt=t+Math.max(680,1350-distance*.7)}if(t>coinAt){spawnCoin();coinAt=t+900+Math.random()*900}if(Math.random()<.14)lines();const rr=runner.getBoundingClientRect();for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.x-=speed*dt;o.el.style.right='auto';o.el.style.left=o.x+'px';const br=o.el.getBoundingClientRect();if(collide(rr,br)){if(o.type==='coin'){energy++;o.el.remove();objects.splice(i,1);continue}else if(!invincible){o.el.remove();objects.splice(i,1);hit();if(!running)return}}if(o.x<-100){o.el.remove();objects.splice(i,1)}}ui();raf=requestAnimationFrame(tick)}
function start(){objects.forEach(o=>o.el.remove());objects=[];running=true;distance=0;energy=0;life=3;speed=310;jumps=0;invincible=false;ui();$('#intro').classList.add('hidden');$('#result').classList.add('hidden');last=performance.now();spawnAt=last+900;coinAt=last+650;raf=requestAnimationFrame(tick)}
$('#start').onclick=start;$('#retry').onclick=start;