const $=(s,c=document)=>c.querySelector(s),stage=$('#stage'),paddle=$('#paddle');let running=false,score=0,combo=0,life=3,last=0,spawnAt=0,speed=175,orbs=[],raf;
const colors=[['#77ffd1','#00aef0'],['#ffe66d','#ff7b54'],['#ff7ce5','#8f5cff'],['#89ff7a','#19bd91']];
function ui(){scoreEl.textContent=score;comboEl.textContent='x'+combo;lifeEl.textContent='♥'.repeat(life)+'♡'.repeat(3-life)}const scoreEl=$('#score'),comboEl=$('#combo'),lifeEl=$('#life');
function movePaddle(x){const r=stage.getBoundingClientRect(),w=paddle.offsetWidth;let px=Math.max(w/2,Math.min(r.width-w/2,x-r.left));paddle.style.left=px+'px'}
stage.addEventListener('pointermove',e=>movePaddle(e.clientX));stage.addEventListener('pointerdown',e=>movePaddle(e.clientX));window.addEventListener('keydown',e=>{if(!running)return;const r=stage.getBoundingClientRect(),cur=paddle.offsetLeft;movePaddle(r.left+cur+(e.key==='ArrowLeft'?-55:e.key==='ArrowRight'?55:0))});
function spawn(){const r=stage.getBoundingClientRect(),bonus=Math.random()<.1,c=colors[Math.floor(Math.random()*colors.length)],el=document.createElement('div');el.className='orb'+(bonus?' bonus':'');el.style.setProperty('--orb1',c[0]);el.style.setProperty('--orb2',c[1]);const o={el,x:24+Math.random()*(r.width-60),y:-45,v:speed+(Math.random()*45),bonus};el.style.left=o.x+'px';el.style.top=o.y+'px';stage.appendChild(el);orbs.push(o)}
function particles(x,y){for(let i=0;i<10;i++){const p=document.createElement('i');p.className='particle';p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--dx',(Math.random()*90-45)+'px');p.style.setProperty('--dy',(Math.random()*70-35)+'px');stage.appendChild(p);setTimeout(()=>p.remove(),600)}}
function finish(win){running=false;cancelAnimationFrame(raf);orbs.forEach(o=>o.el.remove());orbs=[];if(win){let p=JSON.parse(localStorage.getItem('flower-web-missions')||'[false,false,false,false]');p[0]=true;localStorage.setItem('flower-web-missions',JSON.stringify(p));$('#resultIcon').textContent='✦';$('#resultTitle').textContent='光譜反射完成';$('#resultText').textContent='最終分數 '+score+'，最高連擊 '+combo+'。已解鎖 MISSION 01 徽章。'}else{$('#resultIcon').textContent='×';$('#resultTitle').textContent='能量失衡';$('#resultText').textContent='差一點。維持連擊可以更快達成 2500 分。'}$('#result').classList.remove('hidden')}
function tick(t){if(!running)return;const dt=Math.min((t-last)/1000,.035);last=t;if(t>spawnAt){spawn();spawnAt=t+Math.max(340,800-(score/8));}const sr=stage.getBoundingClientRect(),pr=paddle.getBoundingClientRect();for(let i=orbs.length-1;i>=0;i--){const o=orbs[i];o.y+=o.v*dt;o.el.style.top=o.y+'px';const er=o.el.getBoundingClientRect();if(er.bottom>=pr.top&&er.top<pr.bottom&&er.right>pr.left&&er.left<pr.right){combo++;const mult=1+Math.min(4,Math.floor(combo/5));score+=o.bonus?150*mult:70*mult;particles(er.left-sr.left+17,pr.top-sr.top);o.el.remove();orbs.splice(i,1);if(score>=2500)return finish(true);if(combo===8||combo===16||combo===24){speed+=32;$('#levelFlash').classList.remove('show');void $('#levelFlash').offsetWidth;$('#levelFlash').classList.add('show')}}else if(o.y>sr.height+50){o.el.remove();orbs.splice(i,1);life--;combo=0;if(life<=0)return finish(false)}}ui();raf=requestAnimationFrame(tick)}
function start(){orbs.forEach(o=>o.el.remove());orbs=[];score=0;combo=0;life=3;speed=175;ui();$('#intro').classList.add('hidden');$('#result').classList.add('hidden');running=true;last=performance.now();spawnAt=last+250;raf=requestAnimationFrame(tick)}
$('#start').onclick=start;$('#retry').onclick=start;